name: Build jars

on:
  push:
    branches:
      - "1.21.4"
    paths:
      - src/**/*.java
      - src/resources/
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"
      - "!README.md"
      - "!LICENSE"
      - "!CHANGELOG.md"
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  buildJar:
    name: Build jar 1.21.4
    runs-on: ubuntu-latest
    steps:
      - uses: NorthRealm/reusable-actions/SocksProxyClientOfMinecraft/jar@main
        with:
          build-ref: "1.21.4"
          java-version: "21"
          java-distribution: "oracle"