name: Publish release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - uses: NorthRealm/reusable-actions/SocksProxyClientOfMinecraft/release@main
        with:
          tag-ref: ${{ github.ref }}
          java-version: "21"
          java-distribution: "oracle"
          token: ${{ secrets.MODRINTH_TOKEN }}